name: Demo Github Actions Events
run-name: Demo GitHub Actions Events

on:
  # Webhook events
  push:
    branches:
      - main
      - feat/*
  pull_request:
    branches: [main]
  issues:
    types: 
      - opened
      - closed
  # Manual events
  workflow_dispatch:
    inputs:
      yourName:
        description: 
        required: true
        default: My friend
      feelingGood:
        description: 
        required: true
        type: boolean
      howYoyFindGithubActions:
        description: How do you find Github Actions?
        required: true
        type: choice
        options:
          - Awesome
          - Okay
          - nah

jobs:
  Greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Good morning"
      - name: Your name
        run: echo ${{ inputs.yourName }}
      - name: Feeling good
        run: echo ${{ inputs.feelingGood }}
      - name: GitHub action is
        run: echo ${{ inputs.howYoyFindGithubActions }}
