name: Demo 2
run-name: Demo 2 :)

on:
  # Manual events
  workflow_dispatch: 
    inputs:
      yourName:
        description: What's your name?
        required: true
        default: My friend
      feelingGood:
        description: Are you feeling good?
        required: true
        type: boolean
      howYouFindGitHubActions:
        description: How do you find GitHub Actions?
        required: true
        type: choice
        options:
          - Awesome
          - Okay
          - Na

env:
  GREETING_WORD: Hello
  YOUR_NAME: ${{inputs.yourName}}

jobs:
  Greeting:
    runs-on: ubuntu-latest
    env:
      GREETING_WORD: Good afternoon
    steps:
      - name: Say hello
        env:
          GREETING WORD: Good morning
        run: echo $GREETING_WORD
      - name: Your name
        run: echo ${{ inputs.yourName }}
      - name: Feeling good
        run: echo ${{ inputs.feelingGood }}
      - name: print only if you are feeling good
        run: echo "Great! have nice workshop!"
        if: ${{ inputs.feelingGood == true }}
      - name: print only if you are feeling bad
        run: echo "No worries! I'm here with you"
        if: inputs.feelingGood == false
      - name: GitHub Actions is
        run: echo ${{ inputs.howYouFindGitHubActions }}
  Another_Job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo $GREETING_WORD
  
